// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRe_e5eVBvQTjPULp8seDNSzMN-vCk2I',
    appId: '1:23265456224:web:de13ca81098f2852629305',
    messagingSenderId: '23265456224',
    projectId: 'tugas9-73754',
    authDomain: 'tugas9-73754.firebaseapp.com',
    storageBucket: 'tugas9-73754.firebasestorage.app',
    measurementId: 'G-N3KKCLC1L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JCRvWZaCLCOmQ32EORuzryV9ZZhUePM',
    appId: '1:23265456224:android:b5e15b4b89ff3c92629305',
    messagingSenderId: '23265456224',
    projectId: 'tugas9-73754',
    storageBucket: 'tugas9-73754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF0X2zL3L8Ri-d4HC_UA4gPtXWQk6unBE',
    appId: '1:23265456224:ios:b5f87d48ff535081629305',
    messagingSenderId: '23265456224',
    projectId: 'tugas9-73754',
    storageBucket: 'tugas9-73754.firebasestorage.app',
    iosBundleId: 'com.example.tugas9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF0X2zL3L8Ri-d4HC_UA4gPtXWQk6unBE',
    appId: '1:23265456224:ios:b5f87d48ff535081629305',
    messagingSenderId: '23265456224',
    projectId: 'tugas9-73754',
    storageBucket: 'tugas9-73754.firebasestorage.app',
    iosBundleId: 'com.example.tugas9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFRe_e5eVBvQTjPULp8seDNSzMN-vCk2I',
    appId: '1:23265456224:web:953eb11bef4b0ada629305',
    messagingSenderId: '23265456224',
    projectId: 'tugas9-73754',
    authDomain: 'tugas9-73754.firebaseapp.com',
    storageBucket: 'tugas9-73754.firebasestorage.app',
    measurementId: 'G-KLGQ7R0VL7',
  );
}
